In [33]:
import torch
import ai
import random

In [70]:
model1 = torch.load("epoch_23.pt")
model2 = torch.load("epoch_51.pt")
model1,model2

(Model(
   (hidden): Linear(in_features=5, out_features=20, bias=True)
   (output): Linear(in_features=20, out_features=2, bias=True)
   (sigmoid): Sigmoid()
 ),
 Model(
   (hidden): Linear(in_features=5, out_features=20, bias=True)
   (output): Linear(in_features=20, out_features=2, bias=True)
   (sigmoid): Sigmoid()
 ))

<All keys matched successfully>

In [71]:
model1.state_dict(),model2.state_dict()

(OrderedDict([('hidden.weight',
               tensor([[-0.0378,  1.1161, -0.8926,  0.5649,  0.8594],
                       [-0.0758, -0.2232,  0.1721,  0.3959,  0.5356],
                       [-0.5578,  0.0846,  0.0053,  0.3075, -0.9624],
                       [ 0.3676,  0.4635, -0.3611, -0.2580,  0.9842],
                       [ 0.0439, -0.9719,  0.1872,  0.2532,  0.2306],
                       [-0.3300,  0.3199, -0.4425,  1.2702,  0.1252],
                       [-0.1214,  0.2530,  0.5087,  0.2432,  0.4563],
                       [ 0.7235,  0.0909,  0.1977, -0.0199, -1.0124],
                       [ 0.3416, -0.5093, -0.4533,  0.4537,  0.7603],
                       [-0.6977, -0.0067, -0.4434,  1.3913, -0.5693],
                       [ 0.3818, -0.0914, -1.3827, -0.1012, -1.0517],
                       [ 0.1686, -0.1141, -0.5519, -0.9517, -0.7292],
                       [-0.2734, -0.7181,  0.5169,  0.0124, -0.6162],
                       [ 0.2135, -0.0459, -0.6986, -0.8781

In [73]:
model1.state_dict(),model2.state_dict()

(OrderedDict([('hidden.weight',
               tensor([[ 0.0297,  1.1161, -0.8926,  0.6197,  0.8594],
                       [-0.3260, -0.2232,  0.1721,  0.4331,  0.5356],
                       [-0.5578,  0.0846,  0.0238,  0.2640, -0.9599],
                       [ 0.3676,  0.4635, -0.3611, -0.2580,  0.9842],
                       [ 0.1404, -1.1388,  0.4538,  0.2532,  0.3550],
                       [-0.2888,  0.2304, -0.5171,  1.2702, -0.0896],
                       [-0.1178,  0.2530,  0.5087,  0.2358,  0.4569],
                       [ 0.7235,  0.0909,  0.1977, -0.3094, -1.1035],
                       [ 0.5413, -0.5257, -0.4533,  0.4537,  0.7340],
                       [-0.5219,  0.0039, -0.4434,  1.3128, -0.7168],
                       [ 0.3818, -0.0914, -1.3827, -0.1012, -1.0517],
                       [ 0.0218,  0.0110, -0.5519, -0.9517, -0.7292],
                       [-0.2734, -0.8841,  0.6036,  0.0586, -0.6162],
                       [ 0.3396, -0.0663, -0.6986, -0.8781

In [41]:
model1_params

OrderedDict([('hidden.weight',
              tensor([[-0.0378,  1.1161, -0.8926,  0.5649,  0.8594],
                      [-0.0758, -0.2232,  0.1721,  0.3959,  0.5356],
                      [-0.5578,  0.0846,  0.0053,  0.3075, -0.9624],
                      [ 0.3676,  0.4635, -0.3611, -0.2580,  0.9842],
                      [ 0.0439, -0.9719,  0.1872,  0.2532,  0.2306],
                      [-0.3300,  0.3199, -0.4425,  1.2702,  0.1252],
                      [-0.1214,  0.2530,  0.5087,  0.2432,  0.4563],
                      [ 0.7235,  0.0909,  0.1977, -0.0199, -1.0124],
                      [ 0.3416, -0.5093, -0.4533,  0.4537,  0.7603],
                      [-0.6977, -0.0067, -0.4434,  1.3913, -0.5693],
                      [ 0.3818, -0.0914, -1.3827, -0.1012, -1.0517],
                      [ 0.1686, -0.1141, -0.5519, -0.9517, -0.7292],
                      [-0.2734, -0.7181,  0.5169,  0.0124, -0.6162],
                      [ 0.2135, -0.0459, -0.6986, -0.8781, -0.4974],
   